#
# 이 문서에는이 블로그의 설정 정보가 포함되어 있으며 편집하여 블로그를 개인화 할 수 있습니다.，
#

# 귀하의 블로그 이름은 "LOFFER"를 원하는 블로그 이름으로 바꾸십시오. 다음 수정 사항은 유사하게 처리 될 수 있습니다.
# "name : LOFFER", 콜론 뒤의 공백은 생략 할 수 없습니다.
# 파운드 기호 뒤의 텍스트는 설명 문서이며 프로그램에서 읽을 수 없습니다.

# 설명 / 서명
name: soreal13
description: soreal의 개발 블로그

# 웹 사이트 도메인 이름을 입력합니다 (자신의 도메인 이름을 추가하지 않았지만 GitHub 페이지에서 할당 한 도메인 이름을 직접 사용하는 경우 생략 가능)
url: https://soreal13.github.io

# 블로그의 두 번째 수준 도메인 이름 (일반적으로 저장소 이름)을 추가합니다.
# 블로그의 URL：(http://yourusername.github.io/repository-name)
# 하위 "/repository-name"
baseurl:


#
# 다음 설정은 선택 사항입니다.
#

# 블로그 로고 이미지 URL, 권장이미지 크기 300px × 300px
avatar: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/logo.png

# favicon（브라우저탭상）이미지 URL，(64px × 64px) 이하 사용 권장
favicon: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/favicon.png


# 메뉴 버튼
navigation:
  - name: home
    url: /
  - name: about
    url: /about
  - name: archive
    url: /archive
  - name: tags
    url: /tags

# 페이지 당 기사 수
paginate: 8

# 기사 소개를위한 구별 표시
excerpt_separator: <!-- more -->

# 소셜 네트워크 링크，웹 사이트 바닥 글에 아이콘으로 표시됩니다. 선택과목, 생략가능.
footer-links: 
  weibo:  #Weibo 개인 도메인명 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: blueruah@gmail.com
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: https://github.com/soreal13 #https://github.com/<>
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #RSS를 입력하기 만하면 사용할 수 있습니다.
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

# 사이트 바닥 글 텍스트
footer-text: Copyright (c) 2020 soreal13

#
# 댓글 주의, 여러 댓글 영역을 동시에 추가하지 마세요.
#

# Disqus shortname，댓글 영역을 추가하려면 시작. 설명서를 참조하고 자신의 disqus 사이트를 설정.
disqus: #soreal13 #shortname

# 코멘트 영역을 추가하려면 Gitalk 관련 설정을 입력. 자세한 내용은 튜토리얼을 참조
gitalk:
  clientID: 2e47d49f3a28cd1e6eaa
  clientSecret: 7bd68aec92c8b6e3e933be70ab3d9a7cd1ae41b6
  repo: soreal13.github.io
  owner: soreal13

# 시작 Google Analytics web tracking code
google_analytics: G-NFZ0GXC5W9

utteranc:
  repo: # Your github repo path, also see: https://utteranc.es

#
# !! 다음 설정은 변경할 필요가 없습니다.!!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

